apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: techtrends
  template:
    metadata:
      labels:
        name: techtrends
    spec:
      containers:
      - image: thomasrobertz/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.resources.memory }}
          limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: /{{ .Values.readinessProbe.path }}
            port: {{ .Values.containerPort }}