apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: techtrends
  name: techtrends-prod
spec:
  destination:
    namespace: sandbox
    server: https://kubernetes.default.svc
  project: default    
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm
    repoURL: https://github.com/thomasrobertz/techtrends
    targetRevision: HEAD
